# Generated by Django 4.0.10 on 2024-03-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '担当', 'verbose_name_plural': '担当管理'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '担当情報', 'verbose_name_plural': '担当情報管理'},
        ),
    ]
