# Generated by Django 5.1.1 on 2024-09-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_remove_userinfo_is_facebook_userinfo_is_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
