# Generated by Django 5.1.1 on 2024-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('YOUTUBE', 'YOUTUBE'), ('TIKTOK', 'TIKTOK')], default='YOUTUBE', max_length=10)),
                ('youtube_token', models.TextField(blank=True, null=True)),
                ('youtube_client_id', models.TextField(blank=True, null=True)),
                ('youtube_client_secret', models.TextField(blank=True, null=True)),
                ('youtube_project_id', models.TextField(blank=True, null=True)),
                ('youtube_refresh_token', models.TextField(blank=True, null=True)),
                ('youtube_credentials', models.JSONField(blank=True, null=True)),
                ('youtube_credentials_data', models.JSONField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
