# Generated by Django 5.1.1 on 2024-09-09 19:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0007_socialconfig_facebook_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialconfig',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedulevideo',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='schedule_videos/'),
        ),
    ]
