# Generated by Django 5.1.1 on 2024-09-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0008_socialconfig_is_active_socialconfig_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialconfig',
            old_name='instagram_busiess_id',
            new_name='instagram_business_id',
        ),
    ]
