# Generated by Django 5.1.1 on 2024-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0011_socialconfig_twitter_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconfig',
            name='provider',
            field=models.CharField(choices=[('YOUTUBE', 'YOUTUBE'), ('TIKTOK', 'TIKTOK'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER')], default='YOUTUBE', max_length=10),
        ),
    ]
