# Generated by Django 5.1.1 on 2024-09-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0012_alter_socialconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulevideo',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
