# Generated by Django 5.1.1 on 2024-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0013_schedulevideo_twitter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulevideo',
            name='restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulevideo',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
